export const tweetsData = [   
    {
        handle: `@TrollBot66756542 💎`,
        profilePic: `images/troll.jpg`,
        likes: 27,
        retweets: 10,
        tweetText: `Buy Bitcoin, ETH Make 💰💰💰 low low prices. 
            Guaranteed return on investment. HMU DMs open!!`,
        replies: [],
        isLiked: false,
        isRetweeted: false,
        uuid: '4b161eee-c0f5-4545-9c4b-8562944223ee',
        isVerified: false,
    },    
    {
        handle: `@Elon`,
        profilePic: `images/musk.png`,
        likes: 6500,
        retweets: 234,
        tweetText: `I need volunteers for a one-way mission to Mars 🪐. No experience necessary🚀`,
        replies: [
            {
                handle: `@TomCruise`,
                profilePic: `images/tcruise.png`,
                tweetText: `Yes! Sign me up! 😎🛩`,
                isVerified: true,
            },
                  {
                handle: `@ChuckNorris`,
                profilePic: `images/chucknorris.jpeg`,
                tweetText: `I went last year😴`,
                isVerified: true,
            },
        ],
        isLiked: false,
        isRetweeted: false,
        uuid: '3c23454ee-c0f5-9g9g-9c4b-77835tgs2',
        isVerified: true,

    },
        {
        handle: `@NoobCoder12`,
        profilePic: `images/flower.png`,
        likes: 10,
        retweets: 3,
        tweetText: `Are you a coder if you only know HTML?`,
        replies: [
            {
                handle: `@StackOverflower`,
                profilePic: `images/overflow.png`,
                tweetText: `No. Obviosuly not. Go get a job in McDonald's.`,
                isVerified: true,
            },
            {
                handle: `@YummyCoder64`,
                profilePic: `images/love.png`,
                tweetText: `You are wonderful just as you are! ❤️`,
                isVerified: true,
            },
        ],
        isLiked: false,
        isRetweeted: false,
        uuid: '8hy671sff-c0f5-4545-9c4b-1237gyys45',
        isVerified: false,
    },    
      {
        handle: `@proplayer`,
        profilePic: `images/pro.jpg`,
        likes: 5,
        retweets: 3,
        tweetText: `Do you like honey or sugar?`,
        replies: [
            {
                handle: `@TechCrunch`,
                profilePic: `images/techcrunch.svg`,
                tweetText: `No. Obviosuly not. I would use milk.`,
                isVerified: true,
            },
            {
                handle: `@businessMan`,
                profilePic: `images/businessMan.jpg`,
                tweetText: `Are you really asking those things`,
                isVerified: false,
            },
        ],
        isLiked: false,
        isRetweeted: false,
        uuid: '570d3b96-5e81-44fe-881c-624280133980',
        isVerified: true,
    },     
]